//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoAdicional_MXT
    {
        public int idDadoAdicional { get; set; }
        public int idDadoLido { get; set; }
        public Nullable<int> LifeTime { get; set; }
        public Nullable<int> PositionInformation { get; set; }
        public Nullable<int> AccelerometerEvent { get; set; }
        public Nullable<int> AccelerometerValue { get; set; }
        public Nullable<byte> CellPresent { get; set; }
        public Nullable<byte> VoiceCall { get; set; }
        public Nullable<double> LatitudeSad69 { get; set; }
        public Nullable<double> LongitudeSad69 { get; set; }
        public string Utm { get; set; }
        public Nullable<double> Easting { get; set; }
        public Nullable<double> Northing { get; set; }
        public Nullable<byte> TamperingIsOpen { get; set; }
        public Nullable<byte> InternalAlarm { get; set; }
        public Nullable<byte> AccessoryMissing { get; set; }
        public Nullable<double> DetailedSupply { get; set; }
        public Nullable<double> Ad4 { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<byte> PointAnalise { get; set; }
        public Nullable<int> AccessoryCount { get; set; }
        public Nullable<byte> BatteryCharging { get; set; }
        public Nullable<byte> BatteryFailure { get; set; }
        public Nullable<int> PointId { get; set; }
        public Nullable<byte> PointIn { get; set; }
        public Nullable<byte> PointOut { get; set; }
    
        public virtual DadoLido DadoLido { get; set; }
    }
}
