//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoSatelite
    {
        public int idDadoSatelite { get; set; }
        public int idDadoLido { get; set; }
        public int DadoSerial { get; set; }
        public int DadoCSQ { get; set; }
        public int DadoSVN { get; set; }
        public int DadoSNR { get; set; }
        public int DadoHDOP { get; set; }
    
        public virtual DadoLido DadoLido { get; set; }
    }
}
