//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoGSM
    {
        public int idDadoGSM { get; set; }
        public int idDadoLido { get; set; }
        public int DadoSerial { get; set; }
        public string DadoLAC { get; set; }
        public string DadoMNC { get; set; }
        public string DadoMCC { get; set; }
        public string DadoCellId { get; set; }
    
        public virtual DadoLido DadoLido { get; set; }
    }
}
