//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoLido
    {
        public DadoLido()
        {
            this.DadoAcessorios = new HashSet<DadoAcessorio>();
            this.DadoAdicional_MXT = new HashSet<DadoAdicional_MXT>();
            this.DadoGSMs = new HashSet<DadoGSM>();
            this.DadoLivres = new HashSet<DadoLivre>();
            this.DadoSatelites = new HashSet<DadoSatelite>();
        }
    
        public int idDadoLido { get; set; }
        public int Serial { get; set; }
        public int Protocol { get; set; }
        public int MemoryIndex { get; set; }
        public int Hourmeter { get; set; }
        public Nullable<int> PacketReason { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime SystemDate { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<byte> GprsConn { get; set; }
        public Nullable<byte> GpsSignal { get; set; }
        public Nullable<byte> GpsAntFail { get; set; }
        public Nullable<byte> GpsAntDisc { get; set; }
        public Nullable<byte> GpsSleep { get; set; }
        public Nullable<byte> GsmJamming { get; set; }
        public Nullable<byte> Moving { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> PowerSupply { get; set; }
        public Nullable<byte> Ignition { get; set; }
        public Nullable<byte> Panic { get; set; }
        public Nullable<int> Inputs { get; set; }
        public Nullable<int> Outputs { get; set; }
        public Nullable<int> AnalogInputs { get; set; }
        public Nullable<double> BatteryUsed { get; set; }
        public Nullable<int> AntiTheftStatus { get; set; }
        public Nullable<long> Hodometer { get; set; }
        public Nullable<int> Rpm { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<byte> AccessoryExists { get; set; }
        public Nullable<byte> OpenDataExists { get; set; }
        public string Ipv4 { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
        public Nullable<int> PacketSize { get; set; }
    
        public virtual ICollection<DadoAcessorio> DadoAcessorios { get; set; }
        public virtual ICollection<DadoAdicional_MXT> DadoAdicional_MXT { get; set; }
        public virtual ICollection<DadoGSM> DadoGSMs { get; set; }
        public virtual ICollection<DadoLivre> DadoLivres { get; set; }
        public virtual ICollection<DadoSatelite> DadoSatelites { get; set; }
    }
}
