//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoLivre
    {
        public int idDadoLivre { get; set; }
        public int idDadoLido { get; set; }
        public int DadoSerial { get; set; }
        public string DadoString { get; set; }
        public System.DateTime DadoDH { get; set; }
        public System.DateTime DadoDHS { get; set; }
    
        public virtual DadoLido DadoLido { get; set; }
    }
}
