//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoTrackerModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoTrackerContainer : DbContext
    {
        public GoTrackerContainer()
            : base("name=GoTrackerContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Equipamento> Equipamentoes { get; set; }
        public DbSet<Motorista> Motoristas { get; set; }
        public DbSet<Perfil> Perfils { get; set; }
        public DbSet<SimCard> SimCards { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Veiculo> Veiculoes { get; set; }
        public DbSet<DadoAcessorio> DadoAcessorios { get; set; }
        public DbSet<DadoAdicional_MXT> DadoAdicional_MXT { get; set; }
        public DbSet<DadoGSM> DadoGSMs { get; set; }
        public DbSet<DadoLido> DadoLidoes { get; set; }
        public DbSet<DadoLivre> DadoLivres { get; set; }
        public DbSet<DadoSatelite> DadoSatelites { get; set; }
        public DbSet<Ultimo_DadoLido> Ultimo_DadoLido { get; set; }
    }
}
