//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GoTrackerModel", "ClienteCliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.Cliente), "Cliente1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Cliente), true)]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "SimCardEquipamento", "SimCard", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.SimCard), "Equipamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Equipamento), true)]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "EquipamentoVeiculo", "Equipamento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.Equipamento), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GoTrackerWS.Models.Veiculo))]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "MotoristaVeiculo", "Motorista", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.Motorista), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Veiculo), true)]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "UsuarioCliente", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Usuario), "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(GoTrackerWS.Models.Cliente))]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "ClienteVeiculo", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.Cliente), "Veiculo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Veiculo), true)]
[assembly: EdmRelationshipAttribute("GoTrackerModel", "PerfilUsuario", "Perfil", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GoTrackerWS.Models.Perfil), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GoTrackerWS.Models.Usuario), true)]

#endregion

namespace GoTrackerWS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GoTrackerModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GoTrackerModelContainer object using the connection string found in the 'GoTrackerModelContainer' section of the application configuration file.
        /// </summary>
        public GoTrackerModelContainer() : base("name=GoTrackerModelContainer", "GoTrackerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GoTrackerModelContainer object.
        /// </summary>
        public GoTrackerModelContainer(string connectionString) : base(connectionString, "GoTrackerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GoTrackerModelContainer object.
        /// </summary>
        public GoTrackerModelContainer(EntityConnection connection) : base(connection, "GoTrackerModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Equipamento> Equipamentoes
        {
            get
            {
                if ((_Equipamentoes == null))
                {
                    _Equipamentoes = base.CreateObjectSet<Equipamento>("Equipamentoes");
                }
                return _Equipamentoes;
            }
        }
        private ObjectSet<Equipamento> _Equipamentoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Motorista> Motoristas
        {
            get
            {
                if ((_Motoristas == null))
                {
                    _Motoristas = base.CreateObjectSet<Motorista>("Motoristas");
                }
                return _Motoristas;
            }
        }
        private ObjectSet<Motorista> _Motoristas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SimCard> SimCards
        {
            get
            {
                if ((_SimCards == null))
                {
                    _SimCards = base.CreateObjectSet<SimCard>("SimCards");
                }
                return _SimCards;
            }
        }
        private ObjectSet<SimCard> _SimCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Veiculo> Veiculoes
        {
            get
            {
                if ((_Veiculoes == null))
                {
                    _Veiculoes = base.CreateObjectSet<Veiculo>("Veiculoes");
                }
                return _Veiculoes;
            }
        }
        private ObjectSet<Veiculo> _Veiculoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Perfil> Perfils
        {
            get
            {
                if ((_Perfils == null))
                {
                    _Perfils = base.CreateObjectSet<Perfil>("Perfils");
                }
                return _Perfils;
            }
        }
        private ObjectSet<Perfil> _Perfils;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Equipamentoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipamentoes(Equipamento equipamento)
        {
            base.AddObject("Equipamentoes", equipamento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Motoristas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMotoristas(Motorista motorista)
        {
            base.AddObject("Motoristas", motorista);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SimCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimCards(SimCard simCard)
        {
            base.AddObject("SimCards", simCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Veiculoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVeiculoes(Veiculo veiculo)
        {
            base.AddObject("Veiculoes", veiculo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Perfils EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerfils(Perfil perfil)
        {
            base.AddObject("Perfils", perfil);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="clienteId">Initial value of the ClienteId property.</param>
        /// <param name="cNPJ">Initial value of the CNPJ property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        /// <param name="logradouro">Initial value of the Logradouro property.</param>
        /// <param name="cidade">Initial value of the Cidade property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="webSite">Initial value of the WebSite property.</param>
        /// <param name="observacoes">Initial value of the Observacoes property.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nome, global::System.Int32 clienteId, global::System.String cNPJ, global::System.String email, global::System.String telefone, global::System.String logradouro, global::System.String cidade, global::System.String estado, global::System.String webSite, global::System.String observacoes)
        {
            Cliente cliente = new Cliente();
            cliente.Id = id;
            cliente.Nome = nome;
            cliente.ClienteId = clienteId;
            cliente.CNPJ = cNPJ;
            cliente.Email = email;
            cliente.Telefone = telefone;
            cliente.Logradouro = logradouro;
            cliente.Cidade = cidade;
            cliente.Estado = estado;
            cliente.WebSite = webSite;
            cliente.Observacoes = observacoes;
            return cliente;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteId
        {
            get
            {
                return _ClienteId;
            }
            set
            {
                OnClienteIdChanging(value);
                ReportPropertyChanging("ClienteId");
                _ClienteId = StructuralObject.SetValidValue(value, "ClienteId");
                ReportPropertyChanged("ClienteId");
                OnClienteIdChanged();
            }
        }
        private global::System.Int32 _ClienteId;
        partial void OnClienteIdChanging(global::System.Int32 value);
        partial void OnClienteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CNPJ
        {
            get
            {
                return _CNPJ;
            }
            set
            {
                OnCNPJChanging(value);
                ReportPropertyChanging("CNPJ");
                _CNPJ = StructuralObject.SetValidValue(value, false, "CNPJ");
                ReportPropertyChanged("CNPJ");
                OnCNPJChanged();
            }
        }
        private global::System.String _CNPJ;
        partial void OnCNPJChanging(global::System.String value);
        partial void OnCNPJChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false, "Telefone");
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logradouro
        {
            get
            {
                return _Logradouro;
            }
            set
            {
                OnLogradouroChanging(value);
                ReportPropertyChanging("Logradouro");
                _Logradouro = StructuralObject.SetValidValue(value, false, "Logradouro");
                ReportPropertyChanged("Logradouro");
                OnLogradouroChanged();
            }
        }
        private global::System.String _Logradouro;
        partial void OnLogradouroChanging(global::System.String value);
        partial void OnLogradouroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cidade
        {
            get
            {
                return _Cidade;
            }
            set
            {
                OnCidadeChanging(value);
                ReportPropertyChanging("Cidade");
                _Cidade = StructuralObject.SetValidValue(value, false, "Cidade");
                ReportPropertyChanged("Cidade");
                OnCidadeChanged();
            }
        }
        private global::System.String _Cidade;
        partial void OnCidadeChanging(global::System.String value);
        partial void OnCidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WebSite
        {
            get
            {
                return _WebSite;
            }
            set
            {
                OnWebSiteChanging(value);
                ReportPropertyChanging("WebSite");
                _WebSite = StructuralObject.SetValidValue(value, false, "WebSite");
                ReportPropertyChanged("WebSite");
                OnWebSiteChanged();
            }
        }
        private global::System.String _WebSite;
        partial void OnWebSiteChanging(global::System.String value);
        partial void OnWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Observacoes
        {
            get
            {
                return _Observacoes;
            }
            set
            {
                OnObservacoesChanging(value);
                ReportPropertyChanging("Observacoes");
                _Observacoes = StructuralObject.SetValidValue(value, false, "Observacoes");
                ReportPropertyChanged("Observacoes");
                OnObservacoesChanged();
            }
        }
        private global::System.String _Observacoes;
        partial void OnObservacoesChanging(global::System.String value);
        partial void OnObservacoesChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "ClienteCliente", "Cliente1")]
        public EntityCollection<Cliente> Clientes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Cliente>("GoTrackerModel.ClienteCliente", "Cliente1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Cliente>("GoTrackerModel.ClienteCliente", "Cliente1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "ClienteCliente", "Cliente")]
        public Cliente ClientePai
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteCliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteCliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClientePaiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteCliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("GoTrackerModel.ClienteCliente", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "UsuarioCliente", "Usuario")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("GoTrackerModel.UsuarioCliente", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("GoTrackerModel.UsuarioCliente", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "ClienteVeiculo", "Veiculo")]
        public EntityCollection<Veiculo> Veiculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Veiculo>("GoTrackerModel.ClienteVeiculo", "Veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Veiculo>("GoTrackerModel.ClienteVeiculo", "Veiculo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Equipamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Equipamento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="numeroSerie">Initial value of the NumeroSerie property.</param>
        /// <param name="modelo">Initial value of the Modelo property.</param>
        /// <param name="simCardId">Initial value of the SimCardId property.</param>
        public static Equipamento CreateEquipamento(global::System.Int32 id, global::System.String numeroSerie, global::System.String modelo, global::System.Int32 simCardId)
        {
            Equipamento equipamento = new Equipamento();
            equipamento.Id = id;
            equipamento.NumeroSerie = numeroSerie;
            equipamento.Modelo = modelo;
            equipamento.SimCardId = simCardId;
            return equipamento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroSerie
        {
            get
            {
                return _NumeroSerie;
            }
            set
            {
                OnNumeroSerieChanging(value);
                ReportPropertyChanging("NumeroSerie");
                _NumeroSerie = StructuralObject.SetValidValue(value, false, "NumeroSerie");
                ReportPropertyChanged("NumeroSerie");
                OnNumeroSerieChanged();
            }
        }
        private global::System.String _NumeroSerie;
        partial void OnNumeroSerieChanging(global::System.String value);
        partial void OnNumeroSerieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false, "Modelo");
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SimCardId
        {
            get
            {
                return _SimCardId;
            }
            set
            {
                OnSimCardIdChanging(value);
                ReportPropertyChanging("SimCardId");
                _SimCardId = StructuralObject.SetValidValue(value, "SimCardId");
                ReportPropertyChanged("SimCardId");
                OnSimCardIdChanged();
            }
        }
        private global::System.Int32 _SimCardId;
        partial void OnSimCardIdChanging(global::System.Int32 value);
        partial void OnSimCardIdChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Motorista")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Motorista : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Motorista object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="numeroDOC">Initial value of the NumeroDOC property.</param>
        /// <param name="categoriaCNH">Initial value of the CategoriaCNH property.</param>
        /// <param name="sobrenome">Initial value of the Sobrenome property.</param>
        /// <param name="vencimentoCNH">Initial value of the VencimentoCNH property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        /// <param name="celular">Initial value of the Celular property.</param>
        public static Motorista CreateMotorista(global::System.Int32 id, global::System.String nome, global::System.String numeroDOC, global::System.String categoriaCNH, global::System.String sobrenome, global::System.DateTime vencimentoCNH, global::System.String email, global::System.String telefone, global::System.String celular)
        {
            Motorista motorista = new Motorista();
            motorista.Id = id;
            motorista.Nome = nome;
            motorista.NumeroDOC = numeroDOC;
            motorista.CategoriaCNH = categoriaCNH;
            motorista.Sobrenome = sobrenome;
            motorista.VencimentoCNH = vencimentoCNH;
            motorista.Email = email;
            motorista.Telefone = telefone;
            motorista.Celular = celular;
            return motorista;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NumeroDOC
        {
            get
            {
                return _NumeroDOC;
            }
            set
            {
                OnNumeroDOCChanging(value);
                ReportPropertyChanging("NumeroDOC");
                _NumeroDOC = StructuralObject.SetValidValue(value, false, "NumeroDOC");
                ReportPropertyChanged("NumeroDOC");
                OnNumeroDOCChanged();
            }
        }
        private global::System.String _NumeroDOC;
        partial void OnNumeroDOCChanging(global::System.String value);
        partial void OnNumeroDOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CategoriaCNH
        {
            get
            {
                return _CategoriaCNH;
            }
            set
            {
                OnCategoriaCNHChanging(value);
                ReportPropertyChanging("CategoriaCNH");
                _CategoriaCNH = StructuralObject.SetValidValue(value, false, "CategoriaCNH");
                ReportPropertyChanged("CategoriaCNH");
                OnCategoriaCNHChanged();
            }
        }
        private global::System.String _CategoriaCNH;
        partial void OnCategoriaCNHChanging(global::System.String value);
        partial void OnCategoriaCNHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sobrenome
        {
            get
            {
                return _Sobrenome;
            }
            set
            {
                OnSobrenomeChanging(value);
                ReportPropertyChanging("Sobrenome");
                _Sobrenome = StructuralObject.SetValidValue(value, false, "Sobrenome");
                ReportPropertyChanged("Sobrenome");
                OnSobrenomeChanged();
            }
        }
        private global::System.String _Sobrenome;
        partial void OnSobrenomeChanging(global::System.String value);
        partial void OnSobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime VencimentoCNH
        {
            get
            {
                return _VencimentoCNH;
            }
            set
            {
                OnVencimentoCNHChanging(value);
                ReportPropertyChanging("VencimentoCNH");
                _VencimentoCNH = StructuralObject.SetValidValue(value, "VencimentoCNH");
                ReportPropertyChanged("VencimentoCNH");
                OnVencimentoCNHChanged();
            }
        }
        private global::System.DateTime _VencimentoCNH;
        partial void OnVencimentoCNHChanging(global::System.DateTime value);
        partial void OnVencimentoCNHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false, "Telefone");
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, false, "Celular");
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "MotoristaVeiculo", "Veiculo")]
        public EntityCollection<Veiculo> Veiculos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Veiculo>("GoTrackerModel.MotoristaVeiculo", "Veiculo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Veiculo>("GoTrackerModel.MotoristaVeiculo", "Veiculo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Perfil")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Perfil : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Perfil object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="acessoClientes">Initial value of the AcessoClientes property.</param>
        /// <param name="acessoMotoristas">Initial value of the AcessoMotoristas property.</param>
        /// <param name="acessoEquipamentos">Initial value of the AcessoEquipamentos property.</param>
        /// <param name="acessoSimCard">Initial value of the AcessoSimCard property.</param>
        /// <param name="acessoUsuario">Initial value of the AcessoUsuario property.</param>
        /// <param name="acessoVeiculo">Initial value of the AcessoVeiculo property.</param>
        /// <param name="acessoPerfil">Initial value of the AcessoPerfil property.</param>
        public static Perfil CreatePerfil(global::System.Int32 id, global::System.String nome, global::System.Int32 acessoClientes, global::System.Int32 acessoMotoristas, global::System.Int32 acessoEquipamentos, global::System.Int32 acessoSimCard, global::System.Int32 acessoUsuario, global::System.Int32 acessoVeiculo, global::System.Int32 acessoPerfil)
        {
            Perfil perfil = new Perfil();
            perfil.Id = id;
            perfil.Nome = nome;
            perfil.AcessoClientes = acessoClientes;
            perfil.AcessoMotoristas = acessoMotoristas;
            perfil.AcessoEquipamentos = acessoEquipamentos;
            perfil.AcessoSimCard = acessoSimCard;
            perfil.AcessoUsuario = acessoUsuario;
            perfil.AcessoVeiculo = acessoVeiculo;
            perfil.AcessoPerfil = acessoPerfil;
            return perfil;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoClientes
        {
            get
            {
                return _AcessoClientes;
            }
            set
            {
                OnAcessoClientesChanging(value);
                ReportPropertyChanging("AcessoClientes");
                _AcessoClientes = StructuralObject.SetValidValue(value, "AcessoClientes");
                ReportPropertyChanged("AcessoClientes");
                OnAcessoClientesChanged();
            }
        }
        private global::System.Int32 _AcessoClientes;
        partial void OnAcessoClientesChanging(global::System.Int32 value);
        partial void OnAcessoClientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoMotoristas
        {
            get
            {
                return _AcessoMotoristas;
            }
            set
            {
                OnAcessoMotoristasChanging(value);
                ReportPropertyChanging("AcessoMotoristas");
                _AcessoMotoristas = StructuralObject.SetValidValue(value, "AcessoMotoristas");
                ReportPropertyChanged("AcessoMotoristas");
                OnAcessoMotoristasChanged();
            }
        }
        private global::System.Int32 _AcessoMotoristas;
        partial void OnAcessoMotoristasChanging(global::System.Int32 value);
        partial void OnAcessoMotoristasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoEquipamentos
        {
            get
            {
                return _AcessoEquipamentos;
            }
            set
            {
                OnAcessoEquipamentosChanging(value);
                ReportPropertyChanging("AcessoEquipamentos");
                _AcessoEquipamentos = StructuralObject.SetValidValue(value, "AcessoEquipamentos");
                ReportPropertyChanged("AcessoEquipamentos");
                OnAcessoEquipamentosChanged();
            }
        }
        private global::System.Int32 _AcessoEquipamentos;
        partial void OnAcessoEquipamentosChanging(global::System.Int32 value);
        partial void OnAcessoEquipamentosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoSimCard
        {
            get
            {
                return _AcessoSimCard;
            }
            set
            {
                OnAcessoSimCardChanging(value);
                ReportPropertyChanging("AcessoSimCard");
                _AcessoSimCard = StructuralObject.SetValidValue(value, "AcessoSimCard");
                ReportPropertyChanged("AcessoSimCard");
                OnAcessoSimCardChanged();
            }
        }
        private global::System.Int32 _AcessoSimCard;
        partial void OnAcessoSimCardChanging(global::System.Int32 value);
        partial void OnAcessoSimCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoUsuario
        {
            get
            {
                return _AcessoUsuario;
            }
            set
            {
                OnAcessoUsuarioChanging(value);
                ReportPropertyChanging("AcessoUsuario");
                _AcessoUsuario = StructuralObject.SetValidValue(value, "AcessoUsuario");
                ReportPropertyChanged("AcessoUsuario");
                OnAcessoUsuarioChanged();
            }
        }
        private global::System.Int32 _AcessoUsuario;
        partial void OnAcessoUsuarioChanging(global::System.Int32 value);
        partial void OnAcessoUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoVeiculo
        {
            get
            {
                return _AcessoVeiculo;
            }
            set
            {
                OnAcessoVeiculoChanging(value);
                ReportPropertyChanging("AcessoVeiculo");
                _AcessoVeiculo = StructuralObject.SetValidValue(value, "AcessoVeiculo");
                ReportPropertyChanged("AcessoVeiculo");
                OnAcessoVeiculoChanged();
            }
        }
        private global::System.Int32 _AcessoVeiculo;
        partial void OnAcessoVeiculoChanging(global::System.Int32 value);
        partial void OnAcessoVeiculoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AcessoPerfil
        {
            get
            {
                return _AcessoPerfil;
            }
            set
            {
                OnAcessoPerfilChanging(value);
                ReportPropertyChanging("AcessoPerfil");
                _AcessoPerfil = StructuralObject.SetValidValue(value, "AcessoPerfil");
                ReportPropertyChanged("AcessoPerfil");
                OnAcessoPerfilChanged();
            }
        }
        private global::System.Int32 _AcessoPerfil;
        partial void OnAcessoPerfilChanging(global::System.Int32 value);
        partial void OnAcessoPerfilChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "PerfilUsuario", "Usuario")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("GoTrackerModel.PerfilUsuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("GoTrackerModel.PerfilUsuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="SimCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SimCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SimCard object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dDD">Initial value of the DDD property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        /// <param name="pIN">Initial value of the PIN property.</param>
        /// <param name="pUK">Initial value of the PUK property.</param>
        /// <param name="iCCID">Initial value of the ICCID property.</param>
        /// <param name="planoDados">Initial value of the PlanoDados property.</param>
        public static SimCard CreateSimCard(global::System.Int32 id, global::System.String dDD, global::System.String telefone, global::System.String pIN, global::System.String pUK, global::System.String iCCID, global::System.String planoDados)
        {
            SimCard simCard = new SimCard();
            simCard.Id = id;
            simCard.DDD = dDD;
            simCard.Telefone = telefone;
            simCard.PIN = pIN;
            simCard.PUK = pUK;
            simCard.ICCID = iCCID;
            simCard.PlanoDados = planoDados;
            return simCard;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DDD
        {
            get
            {
                return _DDD;
            }
            set
            {
                OnDDDChanging(value);
                ReportPropertyChanging("DDD");
                _DDD = StructuralObject.SetValidValue(value, false, "DDD");
                ReportPropertyChanged("DDD");
                OnDDDChanged();
            }
        }
        private global::System.String _DDD;
        partial void OnDDDChanging(global::System.String value);
        partial void OnDDDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false, "Telefone");
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, false, "PIN");
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PUK
        {
            get
            {
                return _PUK;
            }
            set
            {
                OnPUKChanging(value);
                ReportPropertyChanging("PUK");
                _PUK = StructuralObject.SetValidValue(value, false, "PUK");
                ReportPropertyChanged("PUK");
                OnPUKChanged();
            }
        }
        private global::System.String _PUK;
        partial void OnPUKChanging(global::System.String value);
        partial void OnPUKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ICCID
        {
            get
            {
                return _ICCID;
            }
            set
            {
                OnICCIDChanging(value);
                ReportPropertyChanging("ICCID");
                _ICCID = StructuralObject.SetValidValue(value, false, "ICCID");
                ReportPropertyChanged("ICCID");
                OnICCIDChanged();
            }
        }
        private global::System.String _ICCID;
        partial void OnICCIDChanging(global::System.String value);
        partial void OnICCIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlanoDados
        {
            get
            {
                return _PlanoDados;
            }
            set
            {
                OnPlanoDadosChanging(value);
                ReportPropertyChanging("PlanoDados");
                _PlanoDados = StructuralObject.SetValidValue(value, false, "PlanoDados");
                ReportPropertyChanged("PlanoDados");
                OnPlanoDadosChanged();
            }
        }
        private global::System.String _PlanoDados;
        partial void OnPlanoDadosChanging(global::System.String value);
        partial void OnPlanoDadosChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="sobreNome">Initial value of the SobreNome property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="telefone">Initial value of the Telefone property.</param>
        /// <param name="celular">Initial value of the Celular property.</param>
        /// <param name="dataSuspensao">Initial value of the DataSuspensao property.</param>
        /// <param name="perfilId">Initial value of the PerfilId property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String sobreNome, global::System.String login, global::System.String senha, global::System.String email, global::System.String telefone, global::System.String celular, global::System.String dataSuspensao, global::System.Int32 perfilId)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nome = nome;
            usuario.SobreNome = sobreNome;
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.Email = email;
            usuario.Telefone = telefone;
            usuario.Celular = celular;
            usuario.DataSuspensao = dataSuspensao;
            usuario.PerfilId = perfilId;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SobreNome
        {
            get
            {
                return _SobreNome;
            }
            set
            {
                OnSobreNomeChanging(value);
                ReportPropertyChanging("SobreNome");
                _SobreNome = StructuralObject.SetValidValue(value, false, "SobreNome");
                ReportPropertyChanged("SobreNome");
                OnSobreNomeChanged();
            }
        }
        private global::System.String _SobreNome;
        partial void OnSobreNomeChanging(global::System.String value);
        partial void OnSobreNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false, "Login");
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false, "Senha");
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, false, "Telefone");
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Celular
        {
            get
            {
                return _Celular;
            }
            set
            {
                OnCelularChanging(value);
                ReportPropertyChanging("Celular");
                _Celular = StructuralObject.SetValidValue(value, false, "Celular");
                ReportPropertyChanged("Celular");
                OnCelularChanged();
            }
        }
        private global::System.String _Celular;
        partial void OnCelularChanging(global::System.String value);
        partial void OnCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DataSuspensao
        {
            get
            {
                return _DataSuspensao;
            }
            set
            {
                OnDataSuspensaoChanging(value);
                ReportPropertyChanging("DataSuspensao");
                _DataSuspensao = StructuralObject.SetValidValue(value, false, "DataSuspensao");
                ReportPropertyChanged("DataSuspensao");
                OnDataSuspensaoChanged();
            }
        }
        private global::System.String _DataSuspensao;
        partial void OnDataSuspensaoChanging(global::System.String value);
        partial void OnDataSuspensaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PerfilId
        {
            get
            {
                return _PerfilId;
            }
            set
            {
                OnPerfilIdChanging(value);
                ReportPropertyChanging("PerfilId");
                _PerfilId = StructuralObject.SetValidValue(value, "PerfilId");
                ReportPropertyChanged("PerfilId");
                OnPerfilIdChanged();
            }
        }
        private global::System.Int32 _PerfilId;
        partial void OnPerfilIdChanging(global::System.Int32 value);
        partial void OnPerfilIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "UsuarioCliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.UsuarioCliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.UsuarioCliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.UsuarioCliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("GoTrackerModel.UsuarioCliente", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "PerfilUsuario", "Perfil")]
        public Perfil Perfil
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("GoTrackerModel.PerfilUsuario", "Perfil").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("GoTrackerModel.PerfilUsuario", "Perfil").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Perfil> PerfilReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Perfil>("GoTrackerModel.PerfilUsuario", "Perfil");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Perfil>("GoTrackerModel.PerfilUsuario", "Perfil", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GoTrackerModel", Name="Veiculo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Veiculo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Veiculo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="codigo">Initial value of the Codigo property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="motoristaId">Initial value of the MotoristaId property.</param>
        /// <param name="clienteId">Initial value of the ClienteId property.</param>
        public static Veiculo CreateVeiculo(global::System.Int32 id, global::System.String codigo, global::System.String descricao, global::System.Int32 motoristaId, global::System.Int32 clienteId)
        {
            Veiculo veiculo = new Veiculo();
            veiculo.Id = id;
            veiculo.Codigo = codigo;
            veiculo.Descricao = descricao;
            veiculo.MotoristaId = motoristaId;
            veiculo.ClienteId = clienteId;
            return veiculo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, false, "Codigo");
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false, "Descricao");
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MotoristaId
        {
            get
            {
                return _MotoristaId;
            }
            set
            {
                OnMotoristaIdChanging(value);
                ReportPropertyChanging("MotoristaId");
                _MotoristaId = StructuralObject.SetValidValue(value, "MotoristaId");
                ReportPropertyChanged("MotoristaId");
                OnMotoristaIdChanged();
            }
        }
        private global::System.Int32 _MotoristaId;
        partial void OnMotoristaIdChanging(global::System.Int32 value);
        partial void OnMotoristaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClienteId
        {
            get
            {
                return _ClienteId;
            }
            set
            {
                OnClienteIdChanging(value);
                ReportPropertyChanging("ClienteId");
                _ClienteId = StructuralObject.SetValidValue(value, "ClienteId");
                ReportPropertyChanged("ClienteId");
                OnClienteIdChanged();
            }
        }
        private global::System.Int32 _ClienteId;
        partial void OnClienteIdChanging(global::System.Int32 value);
        partial void OnClienteIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "EquipamentoVeiculo", "Equipamento")]
        public Equipamento Equipamento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipamento>("GoTrackerModel.EquipamentoVeiculo", "Equipamento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipamento>("GoTrackerModel.EquipamentoVeiculo", "Equipamento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipamento> EquipamentoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipamento>("GoTrackerModel.EquipamentoVeiculo", "Equipamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipamento>("GoTrackerModel.EquipamentoVeiculo", "Equipamento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "MotoristaVeiculo", "Motorista")]
        public Motorista Motorista
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Motorista>("GoTrackerModel.MotoristaVeiculo", "Motorista").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Motorista>("GoTrackerModel.MotoristaVeiculo", "Motorista").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Motorista> MotoristaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Motorista>("GoTrackerModel.MotoristaVeiculo", "Motorista");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Motorista>("GoTrackerModel.MotoristaVeiculo", "Motorista", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GoTrackerModel", "ClienteVeiculo", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteVeiculo", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteVeiculo", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("GoTrackerModel.ClienteVeiculo", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("GoTrackerModel.ClienteVeiculo", "Cliente", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
